install.packages("ggplot2")
install.packages("gridExtra")
install.packages("Rcpp")
install.packages("RcppEigen")
install.packages("BH")
install.packages("StanHeaders")
install.packages("rstan", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("rstanarm", dependencies = c("Depends", "Imports", "LinkingTo"))
install.packages("bayesplot")